"""empty message

Revision ID: 024a6a28988b
Revises: 02bdccfa9ab0
Create Date: 2022-07-11 10:01:38.058450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024a6a28988b'
down_revision = '02bdccfa9ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('id_comprador', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedido', 'user', ['id_comprador'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'id_comprador')
    # ### end Alembic commands ###
