"""empty message

Revision ID: 02bdccfa9ab0
Revises: 493882cf4307
Create Date: 2022-07-11 09:59:31.014122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bdccfa9ab0'
down_revision = '493882cf4307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('vendedor_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'producto', 'user', ['vendedor_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.drop_column('producto', 'vendedor_user_id')
    # ### end Alembic commands ###
