"""empty message

Revision ID: 0e3a4b606330
Revises: 2c9257b7e859
Create Date: 2022-07-11 10:03:24.788169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3a4b606330'
down_revision = '2c9257b7e859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direccion', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'direccion', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direccion', type_='foreignkey')
    op.drop_column('direccion', 'user_id')
    # ### end Alembic commands ###
