"""empty message

Revision ID: 2c9257b7e859
Revises: 024a6a28988b
Create Date: 2022-07-11 10:02:40.585851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9257b7e859'
down_revision = '024a6a28988b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cesta', sa.Column('producto_id', sa.Integer(), nullable=True))
    op.add_column('cesta', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cesta', 'producto', ['producto_id'], ['id'])
    op.create_foreign_key(None, 'cesta', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cesta', type_='foreignkey')
    op.drop_constraint(None, 'cesta', type_='foreignkey')
    op.drop_column('cesta', 'user_id')
    op.drop_column('cesta', 'producto_id')
    # ### end Alembic commands ###
