"""empty message

Revision ID: 4577dd402c86
Revises: 6b4c50c71d3d
Create Date: 2022-07-10 08:28:11.542853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4577dd402c86'
down_revision = '6b4c50c71d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_via', sa.String(length=20), nullable=False),
    sa.Column('nombre_via', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=True),
    sa.Column('puerta', sa.String(length=5), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.String(length=8), nullable=False),
    sa.Column('historico', sa.Boolean(), nullable=False),
    sa.Column('id_direccion', sa.Integer(), nullable=True),
    sa.Column('id_comprador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comprador'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_direccion'], ['direccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha_alta', sa.String(length=8), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('vendido', sa.Boolean(), nullable=False),
    sa.Column('foto_producto', sa.Text(), nullable=False),
    sa.Column('descipcion', sa.String(length=3000), nullable=False),
    sa.Column('vendedor_user_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['vendedor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('apellido', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('descipcion', sa.String(length=3000), nullable=False))
    op.add_column('user', sa.Column('dni', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('foto_usuario', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('nacimiento', sa.String(length=8), nullable=False))
    op.add_column('user', sa.Column('nombre', sa.String(length=50), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['dni'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'password',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'nombre')
    op.drop_column('user', 'nacimiento')
    op.drop_column('user', 'foto_usuario')
    op.drop_column('user', 'dni')
    op.drop_column('user', 'descipcion')
    op.drop_column('user', 'apellido')
    op.drop_table('producto')
    op.drop_table('pedido')
    op.drop_table('direccion')
    # ### end Alembic commands ###
