"""empty message

Revision ID: 47561b0d69fd
Revises: f7b2357460d7
Create Date: 2022-07-18 18:01:07.831850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47561b0d69fd'
down_revision = 'f7b2357460d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pedido_id_cesta_fkey', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_id_direccion_fkey', 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'id_direccion')
    op.drop_column('pedido', 'id_cesta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('id_cesta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('id_direccion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pedido_id_direccion_fkey', 'pedido', 'direccion', ['id_direccion'], ['id'])
    op.create_foreign_key('pedido_id_cesta_fkey', 'pedido', 'cesta', ['id_cesta'], ['id'])
    # ### end Alembic commands ###
