"""empty message

Revision ID: 62f8898767f8
Revises: f7930df4400c
Create Date: 2022-07-20 09:23:37.700724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f8898767f8'
down_revision = 'f7930df4400c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pedido_id_cesta_fkey', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_id_direccion_fkey', 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'id_direccion')
    op.drop_column('pedido', 'id_cesta')
    op.alter_column('producto', 'foto_producto',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('user', 'foto_usuario',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'foto_usuario',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('producto', 'foto_producto',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('pedido', sa.Column('id_cesta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('id_direccion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pedido_id_direccion_fkey', 'pedido', 'direccion', ['id_direccion'], ['id'])
    op.create_foreign_key('pedido_id_cesta_fkey', 'pedido', 'cesta', ['id_cesta'], ['id'])
    # ### end Alembic commands ###
