"""empty message

Revision ID: bdbd79292015
Revises: 224b1fd0ef9a
Create Date: 2022-07-15 09:21:36.971423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbd79292015'
down_revision = '224b1fd0ef9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_dni_key', 'user', type_='unique')
    op.drop_column('user', 'dni')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dni', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_dni_key', 'user', ['dni'])
    # ### end Alembic commands ###
