"""empty message

Revision ID: f7930df4400c
Revises: bdbd79292015
Create Date: 2022-07-20 08:34:16.082809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7930df4400c'
down_revision = 'bdbd79292015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('tecnica', sa.String(length=20), nullable=False))
    op.add_column('producto', sa.Column('dimensiones', sa.String(length=10), nullable=False))
    op.drop_column('producto', 'categoria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('categoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('producto', 'dimensiones')
    op.drop_column('producto', 'tecnica')
    # ### end Alembic commands ###
