"""empty message

Revision ID: f7b2357460d7
Revises: bdbd79292015
Create Date: 2022-07-18 12:45:47.822307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b2357460d7'
down_revision = 'bdbd79292015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto', 'foto_producto',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('user', 'foto_usuario',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'foto_usuario',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('producto', 'foto_producto',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
